name: .NET

on:
  push:
    branches: [ mastur ]
    paths: [ 'src/LoveMachine.*/**' ]
  pull_request:
    branches: [ mastur ]
  workflow_dispatch:

jobs:

  build:
  
    uses: ./.github/workflows/build.yml
    with:
      version: '1.0.0'
