name: Post-release workflow

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  update_docs:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: mastur

      - name: Copy readme files
        run: cp doc/*.md .

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: Update readme files
          add: '*.md'
          default_author: github_actions
