name: Integration testing

on:
  workflow_dispatch:

jobs:

  build:

    uses: ./.github/workflows/build.yml
    with:
      version: 1.0.0

  test:

    needs: build
    runs-on: windows-2022
    timeout-minutes: 10

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: src

    - name: Setup Python
      uses: actions/setup-python@v3.1.4
      with:
        python-version: 3.11.4

    - name: Run tests
      run: |
        cd ./IntegrationTest
        pip install -r requirements.txt
        robot ./SecrossphereDemoTestSuite.robot
    
    - name: Copy BepInEx logs
      if: always()
      run: |
        dir ./IntegrationTest/test/scs/BepInEx/
        cp ./IntegrationTest/test/scs/BepInEx/LogOutput.log ./IntegrationTest/bepinex.log

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: src/IntegrationTest
