name: Integration testing

on:
  workflow_dispatch:

jobs:

  build:

    uses: ./.github/workflows/build.yml
    with:
      version: 1.0.0

  test:

    needs: build
    runs-on: windows-2022
    timeout-minutes: 10

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: src

    - name: Setup Python
      uses: actions/setup-python@v3.1.4
      with:
        python-version: 3.11.4

    - name: Run tests
      run: |
        cd ./IntegrationTest
        pip install -r requirements.txt
        robot --outputdir results ./SecrossphereDemoTestSuite.robot

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: src/IntegrationTest/results

  report:

    if: always()
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: .

    - name: Generate test report
      uses: joonvena/robotframework-reporter-action@v2.2
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: results
